// Axe-core sweep across all routes × themes. Targets WCAG 2.2 AA.
// Output: docs/audits/2026-05-09-axe-report.md (human triage table)
//         docs/audits/2026-05-09-axe-raw.json (raw violations for diff)

import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import {
  BASE_URL,
  ROUTES,
  captureFixture,
  newContext,
  resolveRoutePath,
} from "./_lib.mjs";

const THEMES = ["dark", "light"];
const TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"];

const REPO_ROOT = resolve(import.meta.dirname, "..", "..", "..");
const REPORT_PATH = join(REPO_ROOT, "docs", "audits", "2026-05-09-axe-report.md");
const RAW_PATH = join(REPO_ROOT, "docs", "audits", "2026-05-09-axe-raw.json");

const IMPACT_RANK = { critical: 0, serious: 1, moderate: 2, minor: 3 };

async function sweepRoute(browser, route, fixture, theme) {
  const ctx = await newContext(browser, { theme, fixture });
  const page = await ctx.newPage();
  const path = resolveRoutePath(route, fixture);
  await page.goto(`${BASE_URL}${path}`, { waitUntil: "networkidle" });
  // Settle any post-hydration shifts.
  await page.waitForTimeout(250);
  const results = await new AxeBuilder({ page }).withTags(TAGS).analyze();
  await ctx.close();
  return {
    route: route.label,
    path,
    theme,
    violations: results.violations,
    passes: results.passes.length,
    incomplete: results.incomplete.length,
  };
}

function formatReport(allResults) {
  const lines = [
    "# Web UI axe sweep — 2026-05-09",
    "",
    `Generated by \`apps/web/scripts/axe-sweep.mjs\`. WCAG tags: ${TAGS.join(", ")}.`,
    "",
    "## Summary",
    "",
    "| route | theme | violations | critical | serious | moderate | minor | passes |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const r of allResults) {
    const counts = { critical: 0, serious: 0, moderate: 0, minor: 0 };
    for (const v of r.violations) counts[v.impact ?? "minor"]++;
    lines.push(
      `| ${r.route} | ${r.theme} | ${r.violations.length} | ${counts.critical} | ${counts.serious} | ${counts.moderate} | ${counts.minor} | ${r.passes} |`,
    );
  }

  lines.push("");
  lines.push("## Violations");
  lines.push("");

  for (const r of allResults) {
    if (r.violations.length === 0) continue;
    lines.push(`### ${r.route} — ${r.theme} (\`${r.path}\`)`);
    lines.push("");
    const sorted = [...r.violations].sort(
      (a, b) =>
        (IMPACT_RANK[a.impact ?? "minor"] ?? 4) -
          (IMPACT_RANK[b.impact ?? "minor"] ?? 4) || a.id.localeCompare(b.id),
    );
    for (const v of sorted) {
      lines.push(`- **${v.impact ?? "minor"}** \`${v.id}\` — ${v.help} (${v.nodes.length} node${v.nodes.length === 1 ? "" : "s"})`);
      lines.push(`  - ${v.helpUrl}`);
      for (const node of v.nodes.slice(0, 3)) {
        const target = Array.isArray(node.target) ? node.target.join(" ") : String(node.target);
        const summary = (node.failureSummary ?? "")
          .split("\n")
          .map((s) => s.trim())
          .filter(Boolean)
          .join(" / ");
        lines.push(`  - \`${target}\` — ${summary}`);
      }
      if (v.nodes.length > 3) {
        lines.push(`  - …and ${v.nodes.length - 3} more (see raw JSON).`);
      }
    }
    lines.push("");
  }

  const totalCritical = allResults.reduce(
    (sum, r) => sum + r.violations.filter((v) => v.impact === "critical").length,
    0,
  );
  const totalSerious = allResults.reduce(
    (sum, r) => sum + r.violations.filter((v) => v.impact === "serious").length,
    0,
  );
  lines.push("## Acceptance");
  lines.push("");
  lines.push(`Target: zero \`critical\` + zero \`serious\` violations across all routes × both themes.`);
  lines.push("");
  lines.push(`Current: **${totalCritical} critical, ${totalSerious} serious.**`);
  lines.push("");
  return lines.join("\n");
}

async function main() {
  console.log(`Base URL: ${BASE_URL}`);
  const browser = await chromium.launch();
  try {
    console.log("Capturing fixture…");
    const fixture = await captureFixture(browser);

    const all = [];
    for (const route of ROUTES) {
      const fix = route.needsState ? fixture : null;
      for (const theme of THEMES) {
        process.stdout.write(`  ${theme}/${route.label}… `);
        const r = await sweepRoute(browser, route, fix, theme);
        process.stdout.write(`${r.violations.length} violations\n`);
        all.push(r);
      }
    }

    await mkdir(dirname(REPORT_PATH), { recursive: true });
    await writeFile(REPORT_PATH, formatReport(all));
    await writeFile(RAW_PATH, JSON.stringify(all, null, 2));
    const totals = all.reduce(
      (acc, r) => {
        for (const v of r.violations) {
          acc.total++;
          if (v.impact === "critical") acc.critical++;
          if (v.impact === "serious") acc.serious++;
        }
        return acc;
      },
      { total: 0, critical: 0, serious: 0 },
    );
    console.log(
      `\nDone. ${totals.total} violations (${totals.critical} critical, ${totals.serious} serious).`,
    );
    console.log(`Report: ${REPORT_PATH}`);
    console.log(`Raw:    ${RAW_PATH}`);
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
