// Snapshot grid for the identity-pass acceptance:
//   dark theme  — full grid: 6 widths × 5 zoom levels
//   light theme — 100% zoom only across the 6 widths
// Output: docs/audits/snapshots/2026-05-09/<theme>/<route>/<width>w-<zoom>z.png
// Plus an INDEX.md contact-sheet.

import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import {
  BASE_URL,
  ROUTES,
  captureFixture,
  newContext,
  resolveRoutePath,
  setZoom,
} from "./_lib.mjs";

const WIDTHS = [320, 375, 414, 768, 1024, 1440];
const DARK_ZOOMS = [0.8, 1.0, 1.25, 1.5, 2.0];
const LIGHT_ZOOMS = [1.0];

const REPO_ROOT = resolve(import.meta.dirname, "..", "..", "..");
const OUT_DIR = join(REPO_ROOT, "docs", "audits", "snapshots", "2026-05-09");
const INDEX_PATH = join(OUT_DIR, "INDEX.md");

function pct(z) {
  return `${Math.round(z * 100)}`;
}

async function snapRoute(browser, route, fixture, theme, zooms) {
  const ctx = await newContext(browser, { theme, fixture });
  const page = await ctx.newPage();
  const path = resolveRoutePath(route, fixture);
  const captures = [];

  for (const w of WIDTHS) {
    for (const z of zooms) {
      await page.setViewportSize({ width: w, height: 800 });
      await page.goto(`${BASE_URL}${path}`, { waitUntil: "networkidle" });
      await setZoom(page, z);
      // Allow layout to settle after zoom.
      await page.waitForTimeout(150);
      const file = join(OUT_DIR, theme, route.label, `${w}w-${pct(z)}z.png`);
      await mkdir(dirname(file), { recursive: true });
      await page.screenshot({ path: file, fullPage: true });
      captures.push({ theme, route: route.label, width: w, zoom: z, file });
      process.stdout.write(`  ${theme}/${route.label} ${w}w ${pct(z)}z\n`);
    }
  }

  await ctx.close();
  return captures;
}

async function writeIndex(allCaptures) {
  const byRoute = new Map();
  for (const c of allCaptures) {
    if (!byRoute.has(c.route)) byRoute.set(c.route, []);
    byRoute.get(c.route).push(c);
  }

  const lines = [
    "# Web UI snapshot grid — 2026-05-09",
    "",
    `Generated by \`apps/web/scripts/snapshot-grid.mjs\`.`,
    "",
    `- Widths: ${WIDTHS.join(" / ")} px`,
    `- Dark zoom levels: ${DARK_ZOOMS.map(pct).join("% / ")}%`,
    `- Light zoom levels: ${LIGHT_ZOOMS.map(pct).join("% / ")}% (single zoom — light theme verifies color/contrast, layout is shared with dark)`,
    `- Routes covered: ${ROUTES.length} (\`/play/lobby\` and \`/play/room\` skipped — require live WebRTC peer state)`,
    "",
    "## Review protocol",
    "",
    "1. Open each PNG, look for: clipped buttons, horizontal overflow, wrapped labels touching edges, focus-ring artifacts.",
    "2. Flag findings inline below the route's table.",
    "3. Fix, re-run, re-snapshot.",
    "",
  ];

  for (const route of ROUTES) {
    const caps = byRoute.get(route.label) ?? [];
    if (caps.length === 0) continue;
    lines.push(`## ${route.label} (\`${route.path}\`)`);
    lines.push("");
    const themes = Array.from(new Set(caps.map((c) => c.theme)));
    for (const theme of themes) {
      const themeCaps = caps.filter((c) => c.theme === theme);
      const zooms = Array.from(new Set(themeCaps.map((c) => c.zoom))).sort((a, b) => a - b);
      lines.push(`### ${theme}`);
      lines.push("");
      lines.push(`| width \\\\ zoom | ${zooms.map((z) => `${pct(z)}%`).join(" | ")} |`);
      lines.push(`| --- | ${zooms.map(() => "---").join(" | ")} |`);
      for (const w of WIDTHS) {
        const cells = zooms.map((z) => {
          const cap = themeCaps.find((c) => c.width === w && c.zoom === z);
          if (!cap) return "—";
          const rel = cap.file.replace(`${OUT_DIR}/`, "");
          return `[![${w}w ${pct(z)}z](./${rel})](./${rel})`;
        });
        lines.push(`| ${w}px | ${cells.join(" | ")} |`);
      }
      lines.push("");
    }
    lines.push("**Findings:**  _(none yet)_");
    lines.push("");
  }

  await writeFile(INDEX_PATH, lines.join("\n"));
}

async function main() {
  console.log(`Base URL: ${BASE_URL}`);
  const browser = await chromium.launch();
  try {
    console.log("Capturing fixture (visit /play/setup → Start)…");
    const fixture = await captureFixture(browser);
    console.log(`  → game id ${fixture.id}, ${Object.keys(fixture.storage).length} localStorage keys`);

    const all = [];
    for (const route of ROUTES) {
      const fix = route.needsState ? fixture : null;
      console.log(`Snapping ${route.label} (dark)…`);
      all.push(...(await snapRoute(browser, route, fix, "dark", DARK_ZOOMS)));
      console.log(`Snapping ${route.label} (light)…`);
      all.push(...(await snapRoute(browser, route, fix, "light", LIGHT_ZOOMS)));
    }

    await mkdir(OUT_DIR, { recursive: true });
    await writeIndex(all);
    console.log(`\nDone. ${all.length} snapshots → ${OUT_DIR}`);
    console.log(`Index: ${INDEX_PATH}`);
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
